### ISSUE TITLE
How to listen to store update without a component?

### ISSUE THREAD

**Issue by codec-abc** [TimeWarpEngineering/blazor-state#246]
Hi,

As the title say I would like to listen to the store to know when it has been updated to react to it. I cannot find a easy way to do it, could you provide some guidance?

**Comment by ducman** [comment]
I looked at the code and I don't think this is possible unless you want to create a class that inherits from the `BlazorStateComponent` (but not use it like a blazor component) since that is the type is that required when adding a subscription (so you can listen to state changes). 

The author should refactor to use the `IBlazorStateComponent` when adding subscriptions to keep things a bit more robust. Even consider renaming the interface to something that's not a 'component'.

**Comment by StevenTCramer** [comment]
The store would be updated anytime an action is processed.  One would add middleware, either IPipelineBehavior, IRequestPreProcessor or IRequestPostProcessor.

And then in your middleware you can filter for what Actions/State you care about and react accordingly. There are some examples in the repo and in the template project.

https://github.com/TimeWarpEngineering/timewarp-templates/tree/master/Source/TimeWarp.Blazor.Template/templates/TimeWarp.Blazor/Source/Client/Pipeline

**Comment by StevenTCramer** [comment]
@ducman The Subscription mechanism is solely for rerendering components.  It wasn't intended to drive other actions.  If we want to do that I recommend the pipeline, which is where Subscriptions.ReRenderSubscrivers is also called.

But I should be using the Interface instead of the Implementation to register the subscriptions.

Feel free to ping me on Discord if this isn't clear.
